CREATE TABLE IF NOT EXISTS `door_pwd` (
    `id` INT UNSIGNED AUTO_INCREMENT NOT NULL,
    `feedId` INT UNSIGNED UNIQUE,
    `pwd` VARCHAR(255) NOT NULL,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY(`id`),
    FOREIGN KEY(`feedId`) REFERENCES devices(`feedId`) ON DELETE CASCADE
);