CREATE TABLE IF NOT EXISTS `noti` (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    userId INT UNSIGNED NOT NULL,
    ip VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY(id),
    FOREIGN KEY(userId) REFERENCES users(id) ON DELETE CASCADE
)