CREATE TABLE IF NOT EXISTS rooms (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `userId` INT UNSIGNED NOT NULL,
    
    PRIMARY KEY(`id`),
    FOREIGN KEY(`userId`) REFERENCES users(`id`)
)