CREATE TABLE IF NOT EXISTS `plans`(
    `id` INT UNSIGNED AUTO_INCREMENT,
    `sensorId` INT UNSIGNED NOT NULL,
    `lower` VARCHAR(255),
    `upper` VARCHAR(255),
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY(`id`),
    FOREIGN KEY (`sensorId`) REFERENCES sensors(`feedId`) ON DELETE CASCADE
);
